# Starter pipeline


trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
steps:
  
- task: KubernetesManifest@0
  inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'devops-connet'
      manifests: 'nginx-deployment.yaml'