# Starter pipeline


trigger:
  - main
  
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: KubernetesManifest
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'DevOps_PIN'
      manifests: 'nginx-deployment.yaml'
